### ISSUE TITLE
Why is there no setup.py

### ISSUE THREAD

**Issue by Anselmoo** [sourcery-ai/python-best-practices-cookiecutter#11]
> Sorry, maybe I don't get it, but why is no `setup.py` defined for the module?

**Comment by brendanator** [comment]
`setup.py` is needed when publishing packages to pypi. This repo is more focused around writing an application rather than a package

**Comment by Anselmoo** [comment]
@brendanator thx for the feedback!

I really like your `.pre-commit-config.yaml`, it really improved the code-quality.

**Comment by brendanator** [comment]
Fantastic! Glad to hear it
