### ISSUE TITLE
Is using this cookiecutter template "substantial portions of the Software"

### ISSUE THREAD

**Issue by CharString** [sourcery-ai/python-best-practices-cookiecutter#14]
In other words: do reusers have to mark the files in it "Copyright (c) 2019 Sourcery" and does their software have to reproduce it  in their UIs?

I'm asking because I reused parts of it as a base for a [little hack project](https://github.com/CharString/tinkertown-technician).
The files don't form part of the software, but are more configuration of the tools that help build it. But I am redistributing.

**Comment by brendanator** [comment]
No, only the template is licensed. You are free to modify anything it creates, and use any license for it, as you wish
